services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  
  node:    
    image: node:latest    
    container_name: node_service    
    volumes:
      - .:/mainpage    
    working_dir: /mainpage 
    command: npm install && npm run dev    
    ports:      
      - "3000:3000"
